cabal-version:      3.6
name:               hypersmv
version:            0.1.0.0
synopsis:

license:            BSD-3-Clause
license-file:       LICENSE
author:             Hugo Pacheco
maintainer:         hpacheco@di.uminho.pt
copyright:          (c) 2026 Hugo Pacheco

category:           Language

library
    hs-source-dirs: src
    build-depends:
        base, mtl, transformers,
        intern, hashable, safe, digits, mwc-random >= 0.15, random, primitive,
        split, text, bytestring, parsec, prettyprinter,
        directory, filepath, temporary, shelly, process,
        crypton,
        heaps, hashtables, array, keys, containers, unordered-containers, vector, vector-instances, bitvec, deepseq,
        cmdargs, clock
    build-tool-depends:
        alex:alex,
        happy:happy
    exposed-modules:
        Alloy.Gates
        Alloy.Pretty
        Alloy.Syntax
        Alloy.Translate
        Cli.AH
        Cli.Alloy
        Cli.Args
        Cli.Common
        Cli.HyperQube
        Cli.QBF
        Data.BDD
        Data.BDD.Internal
        Data.DD
        Data.DDs
        Data.IDD
        Data.IDD.Internal
        Error
        ExplicitState.APAbstract
        ExplicitState.APInference
        ExplicitState.AutoHyper
        ExplicitState.Enumerate
        ExplicitState.Eval
        ExplicitState.FormulaOptimize
        ExplicitState.Pretty
        ExplicitState.Product
        ExplicitState.Syntax
        ExplicitState.Translate
        ExplicitState.Witness
        HOA.LTL
        HOA.Parser
        HOA.Syntax
        Location
        Parser
        Pretty
        QBF.BitBlast
        QBF.Gates
        QBF.Model
        QBF.Pretty
        QBF.Solver
        QBF.Syntax
        QBF.Unroll
        QBF.Witness
        Smv.Declarative
        Smv.Lexer
        Smv.Packed
        Smv.Parser
        Smv.Pretty
        Smv.Solver
        Smv.Syntax
        Smv.Trace
        Smv.Typing
        Transform.Bexpr
        Transform.Bexpr.CSE
        Transform.Bexpr.Internal
        Transform.Bexpr.Packed
        Transform.Bexpr.Rename
        Transform.DD.Build
        Transform.DD.Packed
        Transform.DD.Split
        Transform.Minimize
        Transform.Normalize
        Transform.Pexpr
        Transform.Substitute
        Utils
    default-language: Haskell2010
    default-extensions:
        RankNTypes
        DataKinds
        DeriveDataTypeable
        DeriveFoldable
        DeriveTraversable
        DeriveFunctor
        DeriveGeneric
        GeneralizedNewtypeDeriving
        OverloadedStrings
        ExtendedDefaultRules
        TupleSections
        ViewPatterns
        ScopedTypeVariables
        MultiParamTypeClasses
        FlexibleContexts
        FlexibleInstances
        UndecidableInstances
        TypeFamilies
        PatternSynonyms
        TypeApplications
        TypeFamilyDependencies
        FunctionalDependencies
        ConstraintKinds
        QuantifiedConstraints
        BangPatterns
        StandaloneDeriving
        TypeSynonymInstances
    ghc-options: -O2 -w -Wincomplete-patterns -Woverlapping-patterns -Wmissing-fields

executable hypersmv
    hs-source-dirs: .
    main-is: Main.hs
    build-depends:
        base, cmdargs, clock,
        mtl, transformers, containers, keys,
        text, bytestring, prettyprinter, hashable,
        crypton,
        directory, filepath, shelly,
        vector,
        hypersmv
    default-language: Haskell2010
    default-extensions:
        DeriveDataTypeable
        OverloadedStrings
        ExtendedDefaultRules
        TupleSections
        ViewPatterns
        ScopedTypeVariables
        RankNTypes
        FlexibleContexts
    ghc-options: -O2 -w -Wincomplete-patterns -Woverlapping-patterns -Wmissing-fields -threaded

